import { useState } from 'react'
import CalcShell from '../../components/calculator/CalcShell'
import BreakdownTable from '../../components/calculator/BreakdownTable'
import AIHintCard from '../../components/calculator/AIHintCard'

// ─── shared helpers ────────────────────────────────────────────
const fmt = n => isNaN(n)||!isFinite(n)?'—':parseFloat(Number(n).toFixed(8)).toString()
const clamp = (v,a,b)=>Math.min(b,Math.max(a,v))
const gcd = (a,b)=>{ a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a }
const lcm = (a,b)=>Math.abs(a*b)/gcd(a,b)

function Sec({title,sub,children}){return(<div style={{background:'var(--bg-card)',border:'0.5px solid var(--border)',borderRadius:14,overflow:'hidden'}}><div style={{padding:'13px 18px',borderBottom:'0.5px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:13,fontWeight:700,color:'var(--text)',fontFamily:"'Space Grotesk',sans-serif"}}>{title}</span>{sub&&<span style={{fontSize:11,color:'var(--text-3)'}}>{sub}</span>}</div><div style={{padding:'16px 18px'}}>{children}</div></div>)}
function Acc({q,a,open,onToggle,color}){return(<div style={{borderBottom:'0.5px solid var(--border)'}}><button onClick={onToggle} style={{width:'100%',display:'flex',justifyContent:'space-between',alignItems:'center',padding:'13px 0',background:'none',border:'none',cursor:'pointer',gap:12,textAlign:'left'}}><span style={{fontSize:13,fontWeight:600,color:'var(--text)',fontFamily:"'DM Sans',sans-serif",lineHeight:1.4}}>{q}</span><span style={{fontSize:18,color,flexShrink:0,transform:open?'rotate(45deg)':'none',transition:'transform .2s'}}>+</span></button>{open&&<p style={{fontSize:12.5,color:'var(--text-2)',lineHeight:1.75,margin:'0 0 13px',fontFamily:"'DM Sans',sans-serif"}}>{a}</p>}</div>)}
function StepsCard({steps,color}){const[exp,setExp]=useState(false);if(!steps||!steps.length)return null;const vis=exp?steps:steps.slice(0,2);return(<div style={{background:'var(--bg-card)',border:'0.5px solid var(--border)',borderRadius:14,overflow:'hidden'}}><div style={{padding:'12px 18px',borderBottom:'0.5px solid var(--border)',display:'flex',justifyContent:'space-between'}}><span style={{fontSize:13,fontWeight:700,color:'var(--text)',fontFamily:"'Space Grotesk',sans-serif"}}>Step-by-step working</span><span style={{fontSize:11,color:'var(--text-3)'}}>{steps.length} steps</span></div><div style={{padding:'16px 18px',display:'flex',flexDirection:'column',gap:14}}>{vis.map((s,i)=>(<div key={i} style={{display:'flex',gap:14,alignItems:'flex-start'}}><div style={{width:26,height:26,borderRadius:'50%',flexShrink:0,background:i===steps.length-1?color:color+'18',border:`1.5px solid ${color}40`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:700,color:i===steps.length-1?'#fff':color}}>{i===steps.length-1?'✓':i+1}</div><div style={{flex:1}}>{s.label&&<div style={{fontSize:10,fontWeight:700,color,textTransform:'uppercase',letterSpacing:'.06em',marginBottom:4}}>{s.label}</div>}<div style={{fontSize:13,fontFamily:"'Space Grotesk',sans-serif",fontWeight:i===steps.length-1?700:500,background:'var(--bg-raised)',padding:'8px 12px',borderRadius:8,border:`0.5px solid ${i===steps.length-1?color+'40':'var(--border)'}`}}>{s.math}</div>{s.note&&<div style={{fontSize:11.5,color:'var(--text-3)',marginTop:4,fontStyle:'italic'}}>↳ {s.note}</div>}</div></div>))}{steps.length>2&&<button onClick={()=>setExp(e=>!e)} style={{padding:'9px',borderRadius:9,border:`1px solid ${color}30`,background:color+'08',color,fontSize:12,fontWeight:600,cursor:'pointer'}}>{exp?'▲ Hide steps':`▼ Show all ${steps.length} steps`}</button>}</div></div>)}
function MathInput({label,value,onChange,hint,color,unit,type='number',placeholder}){const[f,setF]=useState(false);return(<div style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:6}}><label style={{fontSize:12.5,fontWeight:600,color:'var(--text)',fontFamily:"'DM Sans',sans-serif"}}>{label}</label>{hint&&<span style={{fontSize:10,color:'var(--text-3)'}}>{hint}</span>}</div><div style={{display:'flex',alignItems:'stretch',height:44,border:`1.5px solid ${f?color:'var(--border-2)'}`,borderRadius:9,overflow:'hidden',background:'var(--bg-card)',transition:'border-color .15s'}}><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{flex:1,border:'none',background:'transparent',padding:'0 14px',fontSize:16,fontWeight:600,color:'var(--text)',outline:'none',fontFamily:"'Space Grotesk',sans-serif"}}/>{unit&&<div style={{padding:'0 12px',display:'flex',alignItems:'center',background:'var(--bg-raised)',borderLeft:'1px solid var(--border)',fontSize:13,fontWeight:600,color:'var(--text-3)'}}>{unit}</div>}</div></div>)}
function FormulaCard({formula,desc,color}){return(<div style={{background:`linear-gradient(135deg,${color}12,${color}06)`,border:`1px solid ${color}30`,borderRadius:14,padding:'16px 20px',marginBottom:0}}><div style={{fontSize:10,fontWeight:700,color,textTransform:'uppercase',letterSpacing:'.08em',marginBottom:6}}>Formula</div><div style={{fontSize:17,fontWeight:700,color,fontFamily:"'Space Grotesk',sans-serif"}}>{formula}</div>{desc&&<div style={{fontSize:11,color:'var(--text-3)',marginTop:4}}>{desc}</div>}</div>)}
function RealWorld({items}){return(<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{items.map((rw,i)=>(<div key={i} style={{padding:'12px 13px',borderRadius:11,background:rw.color+'08',border:`1px solid ${rw.color}25`}}><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:7}}><span style={{fontSize:18}}>{rw.icon}</span><span style={{fontSize:12,fontWeight:700,color:rw.color}}>{rw.field}</span></div><p style={{fontSize:11.5,color:'var(--text-2)',lineHeight:1.65,margin:'0 0 7px',fontFamily:"'DM Sans',sans-serif"}}>{rw.desc}</p><div style={{fontSize:10,fontWeight:600,color:rw.color,padding:'3px 8px',background:rw.color+'15',borderRadius:6,display:'inline-block'}}>{rw.example}</div></div>))}</div>)}
function MistakesList({items}){return(<div style={{display:'flex',flexDirection:'column',gap:8}}>{items.map((m,i)=>(<div key={i} style={{display:'flex',gap:12,padding:'10px 14px',borderRadius:9,background:'#fee2e210',border:'0.5px solid #ef444420'}}><span style={{fontSize:14,flexShrink:0,color:'#ef4444',fontWeight:700}}>✗</span><span style={{fontSize:12.5,color:'var(--text-2)',lineHeight:1.6}}>{m}</span></div>))}</div>)}
function GlossaryCard({items,color}){const[open,setOpen]=useState(null);return(<>{items.map((g,i)=>(<div key={i} style={{borderBottom:'0.5px solid var(--border)'}}><button onClick={()=>setOpen(open===i?null:i)} style={{width:'100%',display:'flex',justifyContent:'space-between',alignItems:'center',padding:'11px 0',background:'none',border:'none',cursor:'pointer',gap:12,textAlign:'left'}}><div style={{display:'flex',gap:10,alignItems:'center'}}><div style={{width:8,height:8,borderRadius:'50%',background:color,flexShrink:0}}/><span style={{fontSize:13,fontWeight:600,color:'var(--text)',fontFamily:"'DM Sans',sans-serif"}}>{g.term}</span></div><span style={{fontSize:16,color,flexShrink:0,transform:open===i?'rotate(45deg)':'none',transition:'transform .2s'}}>+</span></button>{open===i&&<p style={{fontSize:12.5,color:'var(--text-2)',lineHeight:1.7,margin:'0 0 12px 18px',fontFamily:"'DM Sans',sans-serif"}}>{g.def}</p>}</div>))}</>)}
function BigResult({value,label,unit,color,note}){return(<div style={{background:'var(--bg-card)',border:`1.5px solid ${color}30`,borderRadius:14,padding:'18px 20px',marginBottom:14}}><div style={{fontSize:11,fontWeight:700,color:'var(--text-3)',textTransform:'uppercase',letterSpacing:'.07em',marginBottom:8}}>{label||'Result'}</div><div style={{fontSize:48,fontWeight:700,color,fontFamily:"'Space Grotesk',sans-serif",lineHeight:1,wordBreak:'break-all'}}>{value}{unit}</div>{note&&<div style={{marginTop:12,padding:'10px 13px',background:color+'08',borderRadius:9,border:`1px solid ${color}20`,fontSize:12,color:'var(--text-2)',lineHeight:1.65}}>💡 {note}</div>}</div>)}

// ═══════════════════════════════════════════════════════════════
//  1. PERCENT ERROR CALCULATOR

export default function PercentErrorCalculator({meta,category}){
  const C=category?.color||'#3b82f6'
  const[measured,setMeasured]=useState(4.8)
  const[actual,setActual]=useState(5)
  const[openFaq,setOpenFaq]=useState(null)
  const err=actual===0?null:((Math.abs(measured-actual)/Math.abs(actual))*100)
  const absErr=Math.abs((measured||0)-(actual||0))
  const steps=[
    {label:'Identify values',math:`Measured = ${measured},  Actual (true) = ${actual}`},
    {label:'Find absolute error',math:`|Measured − Actual| = |${measured} − ${actual}| = ${fmt(absErr)}`,note:'Take the absolute value — error is always positive'},
    {label:'Divide by actual value',math:`${fmt(absErr)} ÷ |${actual}| = ${fmt(absErr/Math.abs(actual))}`,note:'Dividing by the true value gives a relative error'},
    {label:'Multiply by 100',math:`${fmt(absErr/Math.abs(actual))} × 100 = ${fmt(err)}%`,note:'Converting to a percentage'},
    {label:'Result',math:`Percent error = ${fmt(err)}%`,note:err&&err<5?'Under 5% — generally acceptable in most science labs':'Over 5% — review your measurement technique'},
  ]
  return(<div style={{display:'flex',flexDirection:'column',gap:20}}>
    <FormulaCard formula="% Error = (|Measured − Actual| / |Actual|) × 100" desc="Always use absolute values — error is never negative" color={C}/>
    <CalcShell left={<>
      <MathInput label="Measured value (your result)" value={measured} onChange={setMeasured} hint="What you got" color={C}/>
      <MathInput label="Actual / accepted value" value={actual} onChange={setActual} hint="The true value" color={C}/>
      <div style={{borderTop:'0.5px solid var(--border)',paddingTop:14,marginTop:4}}>
        <div style={{fontSize:10,fontWeight:700,color:'var(--text-3)',textTransform:'uppercase',letterSpacing:'.07em',marginBottom:10}}>🎯 Lab examples</div>
        {[{m:9.78,a:9.81,l:'Gravity: measured 9.78, actual 9.81 m/s²'},{m:98,a:100,l:'Boiling point: 98°C vs 100°C'},{m:24.5,a:25,l:'Length: 24.5 cm vs 25 cm expected'}].map((ex,i)=>(<button key={i} onClick={()=>{setMeasured(ex.m);setActual(ex.a)}} style={{display:'block',width:'100%',padding:'8px 12px',borderRadius:8,border:'1px solid var(--border-2)',background:'var(--bg-raised)',cursor:'pointer',textAlign:'left',marginBottom:6,fontSize:12,color:'var(--text)',fontFamily:"'DM Sans',sans-serif"}} onMouseEnter={e=>e.currentTarget.style.borderColor=C+'60'} onMouseLeave={e=>e.currentTarget.style.borderColor='var(--border-2)'}>{ex.l}</button>))}
      </div>
    </>} right={<>
      <BigResult value={err===null?'Error':fmt(err)} unit="%" label="Percent error" color={C} note={`Your measurement was off by ${fmt(absErr)} (${fmt(err)}%). ${err&&err<1?'Excellent precision.':err&&err<5?'Acceptable for most experiments.':err&&err<10?'Somewhat inaccurate — check your method.':'High error — significant measurement issue.'}`}/>
      {/* error gauge */}
      <div style={{background:'var(--bg-card)',border:'0.5px solid var(--border)',borderRadius:14,padding:'14px 18px',marginBottom:14}}>
        <div style={{fontSize:12,fontWeight:700,color:'var(--text)',marginBottom:12,fontFamily:"'Space Grotesk',sans-serif"}}>Error scale</div>
        <div style={{display:'flex',height:12,borderRadius:6,overflow:'hidden',marginBottom:8}}>
          {[{w:20,c:'#10b981',l:'Excellent'},{w:30,c:'#f59e0b',l:'OK'},{w:30,c:'#f97316',l:'Poor'},{w:20,c:'#ef4444',l:'Bad'}].map((s,i)=>(<div key={i} style={{flex:s.w,background:s.c,opacity:0.7}}/>))}
        </div>
        <div style={{display:'flex',justifyContent:'space-between',fontSize:9,color:'var(--text-3)',marginBottom:8}}><span>0%</span><span>5%</span><span>10%</span><span>20%+</span></div>
        {err!==null&&<div style={{padding:'8px 12px',background:err<5?'#10b98110':err<10?'#f59e0b10':'#ef444410',borderRadius:8,border:`1px solid ${err<5?'#10b98130':err<10?'#f59e0b30':'#ef444430'}`,fontSize:12,fontWeight:700,color:err<5?'#10b981':err<10?'#f59e0b':'#ef4444'}}>{err<5?'✓ Acceptable (< 5%)':err<10?'⚠ Marginal (5–10%)':'✗ High error (> 10%)'}</div>}
      </div>
      <BreakdownTable title="Summary" rows={[{label:'% Error',value:`${fmt(err)}%`,bold:true,highlight:true,color:C},{label:'Absolute error',value:fmt(absErr)},{label:'Measured',value:measured},{label:'Actual',value:actual}]}/>
      <AIHintCard hint={`Measured: ${measured}, Actual: ${actual} → ${fmt(err)}% error`}/>
    </>}/>
    <StepsCard steps={steps} color={C}/>
    <Sec title="Where percent error matters">
      <RealWorld items={[{icon:'🔬',field:'Science Labs',desc:'Every physics and chemistry experiment requires you to compare your result to the theoretical value. Under 5% is typically acceptable.',example:'Measured g = 9.78, actual 9.81 → 0.3%',color:'#3b82f6'},{icon:'🏭',field:'Manufacturing',desc:'Parts must be machined within a tolerance (e.g. ±0.5%). Percent error quantifies how close production is to the specified dimension.',example:'Target 50mm, made 50.2mm → 0.4% error',color:'#10b981'},{icon:'📡',field:'Sensors & Instruments',desc:'GPS accuracy, thermometer calibration, and pH meter readings all have percent error specs.',example:'GPS target: < 0.01% position error',color:'#f59e0b'},{icon:'🧪',field:'Chemistry Titration',desc:"In titration, your endpoint volume vs the true equivalence volume is the error — precision determines the accuracy of concentration calculations.",example:'Expected 24.8ml, used 25.1ml → 1.2%',color:'#8b5cf6'}]}/>
    </Sec>
    <Sec title="⚠️ Common mistakes"><MistakesList items={['Forgetting to take the absolute value — error is always expressed as positive','Dividing by the measured value instead of the actual/true value','Confusing percent error (accuracy) with percent deviation (precision)']}/></Sec>
    <Sec title="Key terms"><GlossaryCard color={C} items={[{term:'Absolute error',def:'The raw numerical difference between measured and true value, ignoring sign.'},{term:'Relative error',def:'Absolute error divided by the true value — gives the error as a fraction of the true value.'},{term:'Percent error',def:'Relative error × 100 — expresses the error as a percentage of the true value.'},{term:'Accuracy',def:'How close a measurement is to the true value. High accuracy = low percent error.'},{term:'Precision',def:'How consistent repeated measurements are. Precision and accuracy are different — you can be precise but inaccurate.'}]}/></Sec>
    <Sec title="Frequently asked questions">
      {[{q:'What is an acceptable percent error?',a:'In most high school and undergraduate science labs, under 5% is acceptable. In precision engineering or analytical chemistry, under 1% is expected. In some physics experiments (particle physics), errors must be under 0.001%. The acceptable threshold depends entirely on the context.'},{q:'Can percent error be negative?',a:'Technically yes, if you take direction into account (measured > actual vs measured < actual). But in most contexts, percent error is defined using absolute values and is always positive. If direction matters, use "signed percent error" or specify whether your measurement was high or low.'},{q:'What is the difference between percent error and percent difference?',a:'Percent error compares your measurement to a known true value: (|measured − true| / true) × 100. Percent difference compares two measured values with no single truth: (|A − B| / average) × 100. Use percent error when you have a reference; use percent difference when comparing two equivalent measurements.'}].map((f,i)=>(<Acc key={i} q={f.q} a={f.a} open={openFaq===i} onToggle={()=>setOpenFaq(openFaq===i?null:i)} color={C}/>))}
    </Sec>
  </div>)
}

