import { useState, useEffect, useRef } from 'react'
import CalcShell from '../../components/calculator/CalcShell'
import ResultHero from '../../components/calculator/ResultHero'
import BreakdownTable from '../../components/calculator/BreakdownTable'
import AIHintCard from '../../components/calculator/AIHintCard'
import CurrencyDropdown, { CURRENCIES } from '../../components/calculator/CurrencyDropdown'

const fmt = (n,sym='$') => sym+Math.round(Math.max(0,n)).toLocaleString()

const EXAMPLES = [
  { title:'Solar Panels',    desc:'$15k system, saves $150/month',   cost:15000, cashflow:150,  discount:5  },
  { title:'Business Equipment', desc:'$50k machine, earns $2k/month',cost:50000, cashflow:2000, discount:8  },
  { title:'Rental Property', desc:'$200k property, $1,500/mo profit', cost:200000,cashflow:1500, discount:7  },
]

const FAQ = [
  { q:'What is payback period?', a:'Payback period is the time it takes for an investment to generate enough cash flows to recover the initial cost. If you invest $12,000 and receive $1,000/month in returns, the simple payback period is 12 months. It\'s one of the most intuitive measures of investment risk — shorter payback means lower risk.' },
  { q:'What is the difference between simple and discounted payback period?', a:'Simple payback period ignores the time value of money — it treats $1,000 today the same as $1,000 five years from now. Discounted payback period adjusts future cash flows for a discount rate, giving a more accurate picture of how long it truly takes to recover your investment in real terms.' },
  { q:'What is a good payback period?', a:'It depends on the industry and type of investment. For consumer products: 1-2 years. For business equipment: 3-5 years. For real estate: 7-15 years. For infrastructure: 10-25 years. Solar panels typically have 6-10 year payback periods. The key is whether the payback period is shorter than the useful life of the asset.' },
  { q:'What are the limitations of payback period?', a:'Payback period ignores everything that happens after the investment is recovered — a project with 3 year payback that earns for 30 years may be far better than one with 2 year payback that stops after year 4. It also doesn\'t measure profitability, just break-even. Use it alongside ROI and NPV for complete analysis.' },
]

const GLOSSARY = [
  { term:'Payback Period',    def:'The time required to recover the initial investment cost through cash inflows.' },
  { term:'Simple Payback',    def:'Payback period without discounting — ignores the time value of money.' },
  { term:'Discounted Payback',def:'Payback period using discounted (present value) cash flows for more accuracy.' },
  { term:'Cash Flow',         def:'The net income generated by the investment per period — revenue minus operating costs.' },
  { term:'Break-even',        def:'The point where cumulative returns equal the initial investment — ROI = 0%.' },
  { term:'Discount Rate',     def:'The rate used to reduce future cash flows to present value. Reflects opportunity cost.' },
]

function FieldInput({label,hint,value,onChange,prefix,suffix,min=0,max,catColor='#6366f1'}) {
  const [raw,setRaw]=useState(String(value))
  const [focused,setFocused]=useState(false)
  useEffect(()=>{if(!focused)setRaw(String(value))},[value,focused])
  return (
    <div style={{marginBottom:14}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:5}}>
        <label style={{fontSize:12.5,fontWeight:600,color:'var(--text)',fontFamily:"'DM Sans',sans-serif"}}>{label}</label>
        {hint&&<span style={{fontSize:10,color:'var(--text-3)'}}>{hint}</span>}
      </div>
      <div style={{display:'flex',alignItems:'center',gap:6,background:'var(--bg-input,var(--bg-card))',border:`1.5px solid ${focused?catColor:'var(--border)'}`,borderRadius:8,padding:'0 10px',height:38,boxShadow:focused?`0 0 0 3px ${catColor}18`:'none'}}>
        {prefix&&<span style={{fontSize:12,color:'var(--text-3)',fontWeight:600,flexShrink:0}}>{prefix}</span>}
        <input type="text" inputMode="decimal" value={focused?raw:value}
          onChange={e=>{setRaw(e.target.value);const v=parseFloat(e.target.value);if(!isNaN(v))onChange(v)}}
          onFocus={()=>{setFocused(true);setRaw(String(value))}}
          onBlur={()=>{setFocused(false);const v=parseFloat(raw);if(isNaN(v)||raw===''){setRaw(String(min));onChange(min)}else{const c=max!==undefined?Math.min(max,Math.max(min,v)):Math.max(min,v);setRaw(String(c));onChange(c)}}}
          style={{flex:1,border:'none',background:'transparent',fontSize:13,fontWeight:600,color:'var(--text)',padding:0,outline:'none',minWidth:0,fontFamily:"'DM Sans',sans-serif"}} />
        {suffix&&<span style={{fontSize:11,color:'var(--text-3)',fontWeight:500,flexShrink:0}}>{suffix}</span>}
      </div>
    </div>
  )
}
function AccordionItem({q,a,isOpen,onToggle,catColor}) {
  return (
    <div style={{borderBottom:'0.5px solid var(--border)'}}>
      <button onClick={onToggle} style={{width:'100%',display:'flex',justifyContent:'space-between',alignItems:'center',padding:'14px 0',background:'none',border:'none',cursor:'pointer',gap:12,textAlign:'left'}}>
        <span style={{fontSize:13,fontWeight:600,color:'var(--text)',fontFamily:"'DM Sans',sans-serif",lineHeight:1.4}}>{q}</span>
        <span style={{fontSize:18,color:catColor,flexShrink:0,transition:'transform .2s',transform:isOpen?'rotate(45deg)':'rotate(0)',display:'inline-block'}}>+</span>
      </button>
      {isOpen&&<p style={{fontSize:12.5,color:'var(--text-2)',lineHeight:1.75,margin:'0 0 14px',fontFamily:"'DM Sans',sans-serif"}}>{a}</p>}
    </div>
  )
}
function GlossaryTerm({term,def,catColor}) {
  const [open,setOpen]=useState(false)
  return (
    <div onClick={()=>setOpen(o=>!o)} style={{padding:'9px 12px',borderRadius:8,cursor:'pointer',background:open?catColor+'10':'var(--bg-raised)',border:`1px solid ${open?catColor+'30':'var(--border)'}`,transition:'all .15s'}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8}}>
        <span style={{fontSize:12,fontWeight:700,color:open?catColor:'var(--text)',fontFamily:"'Space Grotesk',sans-serif"}}>{term}</span>
        <span style={{fontSize:14,color:catColor,flexShrink:0}}>{open?'−':'+'}</span>
      </div>
      {open&&<p style={{fontSize:11.5,color:'var(--text-2)',lineHeight:1.65,margin:'7px 0 0',fontFamily:"'DM Sans',sans-serif"}}>{def}</p>}
    </div>
  )
}
function Section({title,subtitle,children}) {
  return (
    <div style={{background:'var(--bg-card)',border:'0.5px solid var(--border)',borderRadius:14,overflow:'hidden'}}>
      <div style={{padding:'14px 18px',borderBottom:'0.5px solid var(--border)'}}>
        <div style={{fontSize:13,fontWeight:700,color:'var(--text)',fontFamily:"'Space Grotesk',sans-serif"}}>{title}</div>
        {subtitle&&<div style={{fontSize:11,color:'var(--text-3)',marginTop:2}}>{subtitle}</div>}
      </div>
      <div style={{padding:'16px 18px'}}>{children}</div>
    </div>
  )
}

export default function PaybackPeriod({ meta, category }) {
  const [cost,setCost]=useState(15000)
  const [cashflow,setCashflow]=useState(500)
  const [discount,setDiscount]=useState(5)
  const [currency,setCurrency]=useState(CURRENCIES[0])
  const [openFaq,setOpenFaq]=useState(null)
  const calcRef=useRef(null)
  const sym=currency.symbol
  const catColor=category?.color||'#6366f1'

  // Simple payback (months)
  const simpleMonths = cashflow > 0 ? cost/cashflow : Infinity
  const simpleYrs    = simpleMonths/12

  // Discounted payback — find month where cumulative discounted CF >= cost
  const mr = discount/100/12
  let discountedMonths = Infinity
  let cumDPV = 0
  for (let m=1; m<=600; m++) {
    cumDPV += cashflow/Math.pow(1+mr,m)
    if (cumDPV >= cost) { discountedMonths=m; break }
  }
  const discountedYrs = discountedMonths/12

  // Build cumulative table (yearly)
  const maxYrs = Math.min(Math.ceil(discountedYrs===Infinity?simpleYrs:discountedYrs)+3, 20)
  const tableData = Array.from({length:maxYrs},(_,i)=>{
    const yr=i+1
    const m=yr*12
    const simpleCum=cashflow*m
    let discCum=0
    for(let j=1;j<=m;j++) discCum+=cashflow/Math.pow(1+mr,j)
    return {yr, simpleCum: Math.round(simpleCum), discCum: Math.round(discCum)}
  })

  const hint = cashflow>0
    ? `Simple payback: ${simpleYrs.toFixed(1)} years. Discounted payback at ${discount}%: ${discountedYrs===Infinity?'Never':discountedYrs.toFixed(1)+' years'}. Annual cash flow: ${fmt(cashflow*12,sym)}.`
    : 'Enter a positive monthly cash flow to calculate payback period.'

  function applyExample(ex){setCost(ex.cost);setCashflow(ex.cashflow);setDiscount(ex.discount);setTimeout(()=>calcRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),50)}

  return (
    <div style={{display:'flex',flexDirection:'column',gap:24}}>
      <div ref={calcRef} style={{scrollMarginTop:80}}>
        <CalcShell
          left={<>
            <div style={{fontSize:11,fontWeight:700,color:'var(--text-3)',textTransform:'uppercase',letterSpacing:'.07em',marginBottom:16,paddingBottom:8,borderBottom:'0.5px solid var(--border)'}}>Investment Details</div>
            <CurrencyDropdown currency={currency} setCurrency={setCurrency} catColor={catColor} />
            <FieldInput label="Initial Investment" hint="Total upfront cost" value={cost} onChange={setCost} prefix={sym} min={1} catColor={catColor} />
            <FieldInput label="Monthly Cash Flow" hint="Net monthly return" value={cashflow} onChange={setCashflow} prefix={sym} min={0} catColor={catColor} />
            <FieldInput label="Discount Rate" hint="For discounted payback" value={discount} onChange={setDiscount} suffix="%" min={0} max={50} catColor={catColor} />
            <div style={{display:'flex',gap:10,marginTop:6}}>
              <button style={{flex:1,padding:13,borderRadius:10,border:'none',background:catColor,color:'#fff',fontSize:14,fontWeight:700,cursor:'pointer'}} onMouseEnter={e=>e.currentTarget.style.opacity='.85'} onMouseLeave={e=>e.currentTarget.style.opacity='1'}>Calculate →</button>
              <button onClick={()=>{setCost(15000);setCashflow(500);setDiscount(5)}} style={{padding:'13px 18px',borderRadius:10,border:'1.5px solid var(--border-2)',background:'var(--bg-raised)',color:'var(--text-2)',fontSize:13,fontWeight:500,cursor:'pointer'}} onMouseEnter={e=>{e.currentTarget.style.borderColor='#ef4444';e.currentTarget.style.color='#ef4444'}} onMouseLeave={e=>{e.currentTarget.style.borderColor='var(--border-2)';e.currentTarget.style.color='var(--text-2)'}}>Reset</button>
            </div>
          </>}
          right={<>
            <ResultHero label="Simple Payback Period" value={Math.round(simpleYrs*10)/10} formatter={n=>n.toFixed(1)+' years'} sub={`${Math.round(simpleMonths)} months to recover ${fmt(cost,sym)}`} color={catColor} />
            <BreakdownTable title="Payback Summary" rows={[
              {label:'Initial Investment', value:fmt(cost,sym)},
              {label:'Monthly Cash Flow',  value:fmt(cashflow,sym), color:'#10b981'},
              {label:'Annual Cash Flow',   value:fmt(cashflow*12,sym), color:'#10b981'},
              {label:'Simple Payback',     value:`${simpleYrs.toFixed(1)} yrs`, color:catColor, bold:true},
              {label:`Discounted Payback (${discount}%)`, value:discountedYrs===Infinity?'Never':`${discountedYrs.toFixed(1)} yrs`, color:catColor, highlight:true, bold:true},
            ]} />
            <AIHintCard hint={hint} />
          </>}
        />
      </div>

      <Section title="Cumulative Cash Flow" subtitle="Year-by-year recovery of your investment">
        <div style={{overflowX:'auto'}}>
          <table style={{width:'100%',borderCollapse:'collapse',fontFamily:"'DM Sans',sans-serif"}}>
            <thead><tr>{['Year','Cumulative (Simple)','Cumulative (Discounted)','Status'].map((h,i)=>(
              <th key={h} style={{padding:'9px 12px',fontSize:11,fontWeight:700,color:'var(--text-3)',textAlign:i===0?'left':'right',borderBottom:'1px solid var(--border)',fontFamily:"'Space Grotesk',sans-serif"}}>{h}</th>
            ))}</tr></thead>
            <tbody>
              {tableData.map((r,i)=>{
                const simpleRecovered=r.simpleCum>=cost
                const discRecovered=r.discCum>=cost
                return (
                  <tr key={r.yr} style={{background:i%2===0?'var(--bg-raised)':'transparent'}}>
                    <td style={{padding:'9px 12px',fontSize:12,fontWeight:600,color:catColor}}>Year {r.yr}</td>
                    <td style={{padding:'9px 12px',fontSize:12,color:simpleRecovered?'#10b981':'var(--text)',fontWeight:simpleRecovered?700:400,textAlign:'right'}}>{fmt(r.simpleCum,sym)}</td>
                    <td style={{padding:'9px 12px',fontSize:12,color:discRecovered?'#10b981':'var(--text)',fontWeight:discRecovered?700:400,textAlign:'right'}}>{fmt(r.discCum,sym)}</td>
                    <td style={{padding:'9px 12px',fontSize:11,textAlign:'right',color:discRecovered?'#10b981':'var(--text-3)',fontWeight:discRecovered?700:400}}>
                      {discRecovered?'✓ Recovered':simpleRecovered?'Simple ✓':'Pending'}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </Section>

      <Section title="Real World Examples" subtitle="Click any example to fill the calculator instantly">
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}>
          {EXAMPLES.map((ex,i)=>(
            <button key={i} onClick={()=>applyExample(ex)} style={{padding:14,borderRadius:10,border:'1.5px solid var(--border)',background:'var(--bg-raised)',cursor:'pointer',textAlign:'left',transition:'all .15s'}} onMouseEnter={e=>{e.currentTarget.style.borderColor=catColor;e.currentTarget.style.background=catColor+'10'}} onMouseLeave={e=>{e.currentTarget.style.borderColor='var(--border)';e.currentTarget.style.background='var(--bg-raised)'}}>
              <div style={{fontSize:13,fontWeight:700,color:'var(--text)',marginBottom:4}}>{ex.title}</div>
              <div style={{fontSize:11,color:'var(--text-3)',marginBottom:10,lineHeight:1.4}}>{ex.desc}</div>
              {[['Cost',`${sym}${ex.cost.toLocaleString()}`],['Monthly CF',`${sym}${ex.cashflow.toLocaleString()}`],['Rate',`${ex.discount}%`],['Simple Payback',`${(ex.cost/ex.cashflow/12).toFixed(1)} yrs`]].map(([k,v])=>(
                <div key={k} style={{display:'flex',justifyContent:'space-between'}}>
                  <span style={{fontSize:10,color:'var(--text-3)'}}>{k}</span>
                  <span style={{fontSize:10,fontWeight:600,color:catColor}}>{v}</span>
                </div>
              ))}
              <div style={{marginTop:10,fontSize:10,fontWeight:700,color:catColor}}>Apply example →</div>
            </button>
          ))}
        </div>
      </Section>

      <Section title="Formula Explained" subtitle="Simple vs discounted payback period">
        <div style={{display:'flex',flexDirection:'column',gap:8,marginBottom:14}}>
          {[{label:'Simple Payback',formula:'Payback = Initial Investment / Annual Cash Flow'},{label:'Discounted Payback',formula:'Find n where: Σ [CF / (1+r)^t] ≥ Initial Investment'}].map(f=>(
            <div key={f.label}>
              <div style={{fontSize:10,fontWeight:700,color:'var(--text-3)',textTransform:'uppercase',letterSpacing:'.05em',marginBottom:4}}>{f.label}</div>
              <div style={{background:'var(--bg-raised)',borderRadius:8,padding:'10px 14px',fontFamily:'monospace',fontSize:12,color:catColor,fontWeight:600,overflowX:'auto',whiteSpace:'nowrap'}}>{f.formula}</div>
            </div>
          ))}
        </div>
        <p style={{fontSize:12,color:'var(--text-2)',lineHeight:1.75,margin:0}}>Simple payback divides the investment by annual cash flow — quick but ignores time value. Discounted payback finds the point where the sum of all discounted future cash flows equals the initial investment, giving a more accurate picture of true break-even in real terms.</p>
      </Section>

      <Section title="Key Terms" subtitle="Payback period terminology — click any term">
        <div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8}}>
          {GLOSSARY.map((item,i)=><GlossaryTerm key={i} term={item.term} def={item.def} catColor={catColor} />)}
        </div>
      </Section>

      <Section title="Frequently Asked Questions" subtitle="Everything about payback period">
        {FAQ.map((item,i)=><AccordionItem key={i} q={item.q} a={item.a} isOpen={openFaq===i} onToggle={()=>setOpenFaq(openFaq===i?null:i)} catColor={catColor} />)}
      </Section>
    </div>
  )
}
